// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOD5S2El09qA29o3s-A0tm-zrjA5zeQSE',
    appId: '1:766504733068:web:ec494aea2ededfbeb8aea9',
    messagingSenderId: '766504733068',
    projectId: 'firebasenoti334',
    authDomain: 'fir-noti334.firebaseapp.com',
    storageBucket: 'firebasenoti334.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIusuD4yOnwnnyFtGawF4mbD2xu1mYWJA',
    appId: '1:766504733068:android:2c94888a2ccae7a7b8aea9',
    messagingSenderId: '766504733068',
    projectId: 'firebasenoti334',
    storageBucket: 'firebasenoti334.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJQDRTtmgrqNbCD0VHvaa89tgFqIi0tbY',
    appId: '1:766504733068:ios:3b99e89a5f46620fb8aea9',
    messagingSenderId: '766504733068',
    projectId: 'firebasenoti334',
    storageBucket: 'firebasenoti334.appspot.com',
    iosClientId: '766504733068-1ubhn6es2hjtu7u1kcnge4415ah7moho.apps.googleusercontent.com',
    iosBundleId: 'com.example.vbforntend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJQDRTtmgrqNbCD0VHvaa89tgFqIi0tbY',
    appId: '1:766504733068:ios:3b99e89a5f46620fb8aea9',
    messagingSenderId: '766504733068',
    projectId: 'firebasenoti334',
    storageBucket: 'firebasenoti334.appspot.com',
    iosClientId: '766504733068-1ubhn6es2hjtu7u1kcnge4415ah7moho.apps.googleusercontent.com',
    iosBundleId: 'com.example.vbforntend',
  );
}
